# Auto-generated by tournament.scripts.build_registry
# Generated at: 2026-01-06T04:13:29
# Do not edit manually. Run the builder to update.

from __future__ import annotations

from typing import List, Type

from .cooperator import Cooperator
from .defector import Defector
from .powderflask import Cooperator
from .random_player import Random

# List of player classes to include in tournaments by default.
REGISTERED_PLAYERS: List[Type] = [
    Cooperator,
    Defector,
    Cooperator,
    Random
]


def get_registered_players() -> List[Type]:
    """Return the list of registered player classes."""
    return list(REGISTERED_PLAYERS)

