# Auto-generated by tournament.scripts.build_registry
# Generated at: 2026-03-30T20:41:47
# Do not edit manually. Run the builder to update.

from __future__ import annotations

from typing import List, Type

from .bobisawsome1 import ChuckNorris, LebronJames
from .cooperator import Cooperator
from .defector import Defector
from .joubin03 import JoubinPlayer
from .monicaillner import SuperPunisher
from .nikag2006 import NikaG
from .peterspitz import Peter_Spitz
from .random_player import Random
from .santiagosanchez15 import SmartAggressor, SneakyAggressor

# List of player classes to include in tournaments by default.
REGISTERED_PLAYERS: List[Type] = [
    ChuckNorris,
    LebronJames,
    Cooperator,
    Defector,
    JoubinPlayer,
    SuperPunisher,
    NikaG,
    Peter_Spitz,
    Random,
    SmartAggressor,
    SneakyAggressor
]


def get_registered_players() -> List[Type]:
    """Return the list of registered player classes."""
    return list(REGISTERED_PLAYERS)

